// Date: 8-5-2013 23:38:55
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package hydrocraft.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelElectrostaticGenerator extends ModelHydrocraft
{
	//fields
	ModelRenderer bottom;
	ModelRenderer base;
	ModelRenderer carpet;
	ModelRenderer stick;
	ModelRenderer wool;

	public ModelElectrostaticGenerator()
	{
		textureWidth = 64;
		textureHeight = 32;

		bottom = new ModelRenderer(this, 0, 0);
		bottom.addBox(0F, 0F, 0F, 12, 1, 12);
		bottom.setRotationPoint(-6F, 23F, -6F);
		bottom.setTextureSize(64, 32);
		bottom.mirror = true;
		setRotation(bottom, 0F, 0F, 0F);
		base = new ModelRenderer(this, 0, 13);
		base.addBox(0F, 0F, 0F, 8, 7, 8);
		base.setRotationPoint(-4F, 16F, -4F);
		base.setTextureSize(64, 32);
		base.mirror = true;
		setRotation(base, 0F, 0F, 0F);
		carpet = new ModelRenderer(this, 36, 0);
		carpet.addBox(-2.5F, 0F, -2.5F, 5, 1, 5);
		carpet.setRotationPoint(0F, 15F, 0F);
		carpet.setTextureSize(64, 32);
		carpet.mirror = true;
		setRotation(carpet, 0F, 0F, 0F);
		stick = new ModelRenderer(this, 0, 0);
		stick.addBox(-1F, 0F, -1F, 2, 3, 2);
		stick.setRotationPoint(0F, 8F, 0F);
		stick.setTextureSize(64, 32);
		stick.mirror = true;
		setRotation(stick, 0F, 0F, 0F);
		wool = new ModelRenderer(this, 32, 13);
		wool.addBox(0F, 0F, 0F, 4, 4, 4);
		wool.setRotationPoint(-2F, 11F, -2F);
		wool.setTextureSize(64, 32);
		wool.mirror = true;
		setRotation(wool, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		bottom.render(f5);
		base.render(f5);
		carpet.render(f5);
		stick.render(f5);
		wool.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	@Override
	public void renderInventory() {
		this.renderModel(0.0625f);
	}
	
	public void renderModel(float f5){
		bottom.render(f5);
		base.render(f5);
		carpet.render(f5);
		stick.render(f5);
		wool.render(f5);
	}

}
