// Date: 28-5-2013 21:40:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






/*package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer corner0;
    ModelRenderer corner1;
    ModelRenderer corner2;
    ModelRenderer corner3;
    ModelRenderer center;
    ModelRenderer side0;
    ModelRenderer side1;
    ModelRenderer side2;
    ModelRenderer side3;
    ModelRenderer corner4;
    ModelRenderer corner5;
    ModelRenderer corner6;
    ModelRenderer corner7;
    ModelRenderer side4;
    ModelRenderer side5;
    ModelRenderer side6;
    ModelRenderer side7;
    ModelRenderer side8;
    ModelRenderer side9;
    ModelRenderer side10;
    ModelRenderer side11;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      corner0 = new ModelRenderer(this, 28, 0);
      corner0.addBox(0F, 0F, 0F, 2, 2, 2);
      corner0.setRotationPoint(-8F, 8F, -8F);
      corner0.setTextureSize(64, 32);
      corner0.mirror = true;
      setRotation(corner0, 0F, 0F, 0F);
      corner1 = new ModelRenderer(this, 28, 0);
      corner1.addBox(0F, 0F, 0F, 2, 2, 2);
      corner1.setRotationPoint(-8F, 8F, 8F);
      corner1.setTextureSize(64, 32);
      corner1.mirror = true;
      setRotation(corner1, 0F, 1.570796F, 0F);
      corner2 = new ModelRenderer(this, 28, 0);
      corner2.addBox(0F, 0F, 0F, 2, 2, 2);
      corner2.setRotationPoint(8F, 8F, 8F);
      corner2.setTextureSize(64, 32);
      corner2.mirror = true;
      setRotation(corner2, 0F, 3.141593F, 0F);
      corner3 = new ModelRenderer(this, 28, 0);
      corner3.addBox(0F, 0F, 0F, 2, 2, 2);
      corner3.setRotationPoint(8F, 8F, -8F);
      corner3.setTextureSize(64, 32);
      corner3.mirror = true;
      setRotation(corner3, 0F, -1.570796F, 0F);
      center = new ModelRenderer(this, 0, 4);
      center.addBox(0F, 0F, 0F, 12, 12, 12);
      center.setRotationPoint(-6F, 10F, -6F);
      center.setTextureSize(64, 32);
      center.mirror = true;
      setRotation(center, 0F, 0F, 0F);
      side0 = new ModelRenderer(this, 0, 0);
      side0.addBox(0F, 0F, 0F, 12, 2, 2);
      side0.setRotationPoint(-6F, 8F, -8F);
      side0.setTextureSize(64, 32);
      side0.mirror = true;
      setRotation(side0, 0F, 0F, 0F);
      side1 = new ModelRenderer(this, 0, 0);
      side1.addBox(0F, 0F, 0F, 12, 2, 2);
      side1.setRotationPoint(-6F, 8F, 6F);
      side1.setTextureSize(64, 32);
      side1.mirror = true;
      setRotation(side1, 0F, 0F, 0F);
      side2 = new ModelRenderer(this, 0, 0);
      side2.addBox(0F, 0F, 0F, 12, 2, 2);
      side2.setRotationPoint(-8F, 8F, 6F);
      side2.setTextureSize(64, 32);
      side2.mirror = true;
      setRotation(side2, 0F, 1.570796F, 0F);
      side3 = new ModelRenderer(this, 0, 0);
      side3.addBox(0F, 0F, 0F, 12, 2, 2);
      side3.setRotationPoint(6F, 8F, 6F);
      side3.setTextureSize(64, 32);
      side3.mirror = true;
      setRotation(side3, 0F, 1.570796F, 0F);
      corner4 = new ModelRenderer(this, 28, 0);
      corner4.addBox(0F, 0F, 0F, 2, 2, 2);
      corner4.setRotationPoint(8F, 24F, -8F);
      corner4.setTextureSize(64, 32);
      corner4.mirror = true;
      setRotation(corner4, 0F, 0F, 3.141593F);
      corner5 = new ModelRenderer(this, 28, 0);
      corner5.addBox(0F, 0F, 0F, 2, 2, 2);
      corner5.setRotationPoint(-8F, 24F, -8F);
      corner5.setTextureSize(64, 32);
      corner5.mirror = true;
      setRotation(corner5, 0F, 1.570796F, 3.141593F);
      corner6 = new ModelRenderer(this, 28, 0);
      corner6.addBox(0F, 0F, 0F, 2, 2, 2);
      corner6.setRotationPoint(-8F, 24F, 8F);
      corner6.setTextureSize(64, 32);
      corner6.mirror = true;
      setRotation(corner6, 0F, 3.141593F, 3.141593F);
      corner7 = new ModelRenderer(this, 28, 0);
      corner7.addBox(0F, 0F, 0F, 2, 2, 2);
      corner7.setRotationPoint(8F, 24F, 8F);
      corner7.setTextureSize(64, 32);
      corner7.mirror = true;
      setRotation(corner7, 0F, -1.570796F, 3.141593F);
      side4 = new ModelRenderer(this, 0, 0);
      side4.addBox(0F, 0F, 0F, 12, 2, 2);
      side4.setRotationPoint(-8F, 22F, 6F);
      side4.setTextureSize(64, 32);
      side4.mirror = true;
      setRotation(side4, 0F, 1.570796F, 0F);
      side5 = new ModelRenderer(this, 0, 0);
      side5.addBox(0F, 0F, 0F, 12, 2, 2);
      side5.setRotationPoint(6F, 22F, 6F);
      side5.setTextureSize(64, 32);
      side5.mirror = true;
      setRotation(side5, 0F, 1.570796F, 0F);
      side6 = new ModelRenderer(this, 0, 0);
      side6.addBox(0F, 0F, 0F, 12, 2, 2);
      side6.setRotationPoint(-6F, 22F, -8F);
      side6.setTextureSize(64, 32);
      side6.mirror = true;
      setRotation(side6, 0F, 0F, 0F);
      side7 = new ModelRenderer(this, 0, 0);
      side7.addBox(0F, 0F, 0F, 12, 2, 2);
      side7.setRotationPoint(8F, 10F, 6F);
      side7.setTextureSize(64, 32);
      side7.mirror = true;
      setRotation(side7, 0F, 0F, 1.570796F);
      side8 = new ModelRenderer(this, 0, 0);
      side8.addBox(0F, 0F, 0F, 12, 2, 2);
      side8.setRotationPoint(8F, 10F, -8F);
      side8.setTextureSize(64, 32);
      side8.mirror = true;
      setRotation(side8, 0F, 0F, 1.570796F);
      side9 = new ModelRenderer(this, 0, 0);
      side9.addBox(0F, 0F, 0F, 12, 2, 2);
      side9.setRotationPoint(-6F, 10F, 6F);
      side9.setTextureSize(64, 32);
      side9.mirror = true;
      setRotation(side9, 0F, 0F, 1.570796F);
      side10 = new ModelRenderer(this, 0, 0);
      side10.addBox(0F, 0F, 0F, 12, 2, 2);
      side10.setRotationPoint(-6F, 10F, -8F);
      side10.setTextureSize(64, 32);
      side10.mirror = true;
      setRotation(side10, 0F, 0F, 1.570796F);
      side11 = new ModelRenderer(this, 0, 0);
      side11.addBox(0F, 0F, 0F, 12, 2, 2);
      side11.setRotationPoint(-6F, 22F, 6F);
      side11.setTextureSize(64, 32);
      side11.mirror = true;
      setRotation(side11, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    corner0.render(f5);
    corner1.render(f5);
    corner2.render(f5);
    corner3.render(f5);
    center.render(f5);
    side0.render(f5);
    side1.render(f5);
    side2.render(f5);
    side3.render(f5);
    corner4.render(f5);
    corner5.render(f5);
    corner6.render(f5);
    corner7.render(f5);
    side4.render(f5);
    side5.render(f5);
    side6.render(f5);
    side7.render(f5);
    side8.render(f5);
    side9.render(f5);
    side10.render(f5);
    side11.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}*/
