// Date: 24-5-2013 01:13:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






/*package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer bottom;
    ModelRenderer tank;
    ModelRenderer trunk;
    ModelRenderer arm0;
    ModelRenderer arm1;
    ModelRenderer arm2;
    ModelRenderer arm3;
    ModelRenderer dripper0;
    ModelRenderer dripper1;
    ModelRenderer dripper2;
    ModelRenderer dripper3;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      bottom = new ModelRenderer(this, 0, 14);
      bottom.addBox(0F, 0F, 0F, 16, 2, 16);
      bottom.setRotationPoint(-8F, 22F, -8F);
      bottom.setTextureSize(64, 32);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      tank = new ModelRenderer(this, 40, 0);
      tank.addBox(0F, 0F, 0F, 6, 4, 6);
      tank.setRotationPoint(-3F, 18F, -3F);
      tank.setTextureSize(64, 32);
      tank.mirror = true;
      setRotation(tank, 0F, 0F, 0F);
      trunk = new ModelRenderer(this, 0, 0);
      trunk.addBox(-2F, 0F, -2F, 4, 10, 4);
      trunk.setRotationPoint(0F, 8F, 0F);
      trunk.setTextureSize(64, 32);
      trunk.mirror = true;
      setRotation(trunk, 0F, 0F, 0F);
      arm0 = new ModelRenderer(this, 16, 0);
      arm0.addBox(-1F, 0F, -5F, 2, 2, 5);
      arm0.setRotationPoint(-2F, 10F, 0F);
      arm0.setTextureSize(64, 32);
      arm0.mirror = true;
      setRotation(arm0, 0F, 1.570796F, 0F);
      arm1 = new ModelRenderer(this, 16, 0);
      arm1.addBox(0F, 0F, 0F, 2, 2, 5);
      arm1.setRotationPoint(-1F, 10F, 2F);
      arm1.setTextureSize(64, 32);
      arm1.mirror = true;
      setRotation(arm1, 0F, 0F, 0F);
      arm2 = new ModelRenderer(this, 16, 0);
      arm2.addBox(0F, 0F, 0F, 2, 2, 5);
      arm2.setRotationPoint(2F, 10F, 1F);
      arm2.setTextureSize(64, 32);
      arm2.mirror = true;
      setRotation(arm2, 0F, 1.570796F, 0F);
      arm3 = new ModelRenderer(this, 16, 0);
      arm3.addBox(0F, 0F, 0F, 2, 2, 5);
      arm3.setRotationPoint(-1F, 10F, -7F);
      arm3.setTextureSize(64, 32);
      arm3.mirror = true;
      setRotation(arm3, 0F, 0F, 0F);
      dripper0 = new ModelRenderer(this, 0, 0);
      dripper0.addBox(-0.5F, 0F, -0.5F, 1, 3, 1);
      dripper0.setRotationPoint(-6F, 12F, 0F);
      dripper0.setTextureSize(64, 32);
      dripper0.mirror = true;
      setRotation(dripper0, 0F, 0F, 0F);
      dripper1 = new ModelRenderer(this, 0, 0);
      dripper1.addBox(-0.5F, 0F, -0.5F, 1, 3, 1);
      dripper1.setRotationPoint(6F, 12F, 0F);
      dripper1.setTextureSize(64, 32);
      dripper1.mirror = true;
      setRotation(dripper1, 0F, 0F, 0F);
      dripper2 = new ModelRenderer(this, 0, 0);
      dripper2.addBox(-0.5F, 0F, -0.5F, 1, 3, 1);
      dripper2.setRotationPoint(0F, 12F, -6F);
      dripper2.setTextureSize(64, 32);
      dripper2.mirror = true;
      setRotation(dripper2, 0F, 0F, 0F);
      dripper3 = new ModelRenderer(this, 0, 0);
      dripper3.addBox(-0.5F, 0F, -0.5F, 1, 3, 1);
      dripper3.setRotationPoint(0F, 12F, 6F);
      dripper3.setTextureSize(64, 32);
      dripper3.mirror = true;
      setRotation(dripper3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bottom.render(f5);
    tank.render(f5);
    trunk.render(f5);
    arm0.render(f5);
    arm1.render(f5);
    arm2.render(f5);
    arm3.render(f5);
    dripper0.render(f5);
    dripper1.render(f5);
    dripper2.render(f5);
    dripper3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}*/
